version: '3'

services:
  mongo:
    image: mongo:4.0
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - ./data/mongo:/data/db
      - ./data/mongo_config:/data/configdb
    ports:
      - 27017:27017

  api:
    build: .
    command: invoke start-api
    environment:
      - MONGO=mongo
    volumes:
      - ./invoke.yaml:/simple_backend/invoke.yaml
    ports:
      - 8000:8000
